eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8222
spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: client
          uri: http://client:8080
          predicates:
            - Path=/api/clients/**
        - id: blog
          uri: http://order:8081
          predicates:
            - Path=/api/order/**
        - id: product
          uri: http://product:8082
          predicates:
            - Path=/api/product/**
