eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8222
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: client
          uri: http://localhost:8080
          predicates:
            - Path=/api/client/**
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/api/order/**
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**
        - id: category
          uri: http://localhost:8082
          predicates:
            - Path=/api/category/**
